# Generated by Django 4.2.5 on 2023-12-25 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_userprofile_library_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_expiry',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 17, 8, 40, 946622, tzinfo=datetime.timezone.utc)),
        ),
    ]
