# Generated by Django 4.2.5 on 2023-12-25 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_userprofile_membership_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fines',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='loan_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership_expiry',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 17, 14, 56, 835086, tzinfo=datetime.timezone.utc)),
        ),
    ]
