# Generated by Django 4.2.5 on 2023-12-26 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_userprofile_membership_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_expiry',
            field=models.DateField(default=datetime.datetime(2024, 12, 25, 14, 47, 24, 297711, tzinfo=datetime.timezone.utc)),
        ),
    ]
