# Generated by Django 4.2.5 on 2023-12-27 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_userprofile_membership_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_expiry',
            field=models.DateField(default=datetime.datetime(2024, 12, 26, 1, 59, 50, 302597, tzinfo=datetime.timezone.utc)),
        ),
    ]
