# Generated by Django 4.2.5 on 2023-12-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_userprofile_membership_expiry'),
        ('books', '0008_alter_userprofile_membership_expiry_and_more'),
    ]

    operations = [
    ]
