# Generated by Django 4.2.5 on 2023-12-29 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_merge_20231229_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_expiry',
            field=models.DateField(default=datetime.datetime(2024, 12, 28, 3, 12, 51, 149589, tzinfo=datetime.timezone.utc)),
        ),
    ]
