# Generated by Django 4.2.5 on 2024-01-09 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_userprofile_membership_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publication_date', models.DateField(verbose_name='出版日期')),
                ('category', models.CharField(max_length=100, verbose_name='类别')),
                ('in_stock', models.IntegerField(default=0, verbose_name='库存数量')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 8, 7, 29, 33, 194815, tzinfo=datetime.timezone.utc)),
        ),
    ]
