# Generated by Django 4.2.5 on 2024-01-12 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_userprofile_membership_expiry_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 11, 12, 24, 21, 669791, tzinfo=datetime.timezone.utc)),
        ),
    ]
