# Generated by Django 4.2.5 on 2024-01-23 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_cover_book_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 2, 0, 39, 312589, tzinfo=datetime.timezone.utc)),
        ),
    ]
